# Generated by Django 4.0.3 on 2023-11-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0009_excelfile_image_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demand_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
