# Generated by Django 4.0.3 on 2023-11-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0011_rename_material_2_product_specification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suface_finish',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='surface_protection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
