# Generated by Django 4.0.3 on 2023-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0013_alter_product_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('1', 'Import'), ('2', 'Export')], default=1, max_length=2),
        ),
    ]
