# Generated by Django 4.0.3 on 2023-12-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0015_files_delete_excelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
