# Generated by Django 4.0.3 on 2023-12-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsApp', '0020_alter_invoice_item_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='imsApp.warehouse'),
            preserve_default=False,
        ),
    ]
